import UI_for_word_embeddings
import UI_for_prediction
import Ngram_and_NextWord_Prediction
import Co_occu_matrix_to_vec

__all__ = [UI_for_word_embeddings,UI_for_prediction,Ngram_and_NextWord_Prediction,Co_occu_matrix_to_vec]
